### ISSUE TITLE
Electricity Price for Electric battery storage

### ISSUE THREAD

**Issue by lucanicolienel** [ADGEfficiency/energy-py#38]
Hi Adam, 
I am just trying your demo on Electric battery storage, but there is something strange with my results.
The Electricity price in "observation.csv" are different from results in your demo.

your demo:
![image](https://user-images.githubusercontent.com/43605453/46405788-a31cb200-c709-11e8-9fd7-153041ac56d2.png)

results with "observation.csv":
![image](https://user-images.githubusercontent.com/43605453/46405818-bf205380-c709-11e8-9878-e109c78f549f.png)

Can you also help me to understand what represent the diffrent columns (
C_forecast_electricity_price_hh_0   [$/MWh] | C_forecast_electricity_price_hh_1 [$/MWh] | C_forecast_electricity_price_hh_2 [$/MWh] | C_forecast_electricity_price_hh_3 [$/MWh])?
Are forecast for the following 1,2,3 hours?

Best regards,

Luca

**Comment by ADGEfficiency** [comment]
Hi Luca,

I've made changes to the electricity price data - mostly to make it more interesting (i.e. more spikes).  You do raise an interesting point about consistently of package data though - I'll have a think about this.

The columns are the forecasts for the next half hours - 0 being the current, 1 being the next etc.  

Let me know if you have any more questions - Adam.

**Comment by lucanicolienel** [comment]
Thanks Adam.

In this moment I would like to use your implementation of DPL Agent, but with a custom environment.
I would like to model a HVAC system and I need to develop this enviroment.

Luca

**Comment by lucanicolienel** [comment]
Hi Adam, 
when you talk about  open source simulation models, do you mean like Energy Plus software?
